import turtle,time
wn=turtle.Screen()
############################################################
turtle.up()
turtle.goto(-190,0)
turtle.down()
time.sleep(6)
for i in range(2):
	turtle.color("green")
	turtle.begin_fill()
	turtle.forward(420)
	turtle.left(90)
	turtle.forward(80)
	turtle.left(90)
	turtle.end_fill()
turtle.up()
turtle.left(90)
turtle.forward(80)
turtle.down()
for i in range(2):
	turtle.color("white")
	turtle.begin_fill()
	turtle.forward(80)
	turtle.right(90)
	turtle.forward(420)
	turtle.right(90)
	turtle.end_fill()
turtle.up()
turtle.forward(80)
turtle.down()
for i in range(2):
	turtle.color("orange")
	turtle.begin_fill()
	turtle.forward(80)
	turtle.right(90)
	turtle.forward(420)
	turtle.right(90)
	turtle.end_fill()
############################################################
turtle.up()
turtle.right(90)
turtle.forward(180)
turtle.right(90)
turtle.forward(40)
turtle.down()
turtle.color("blue")
turtle.circle(40)
############################################################
for i in range(25):
	turtle.up()
	turtle.setpos(28.00,120.00)
	turtle.down()
	turtle.forward(40)
	turtle.left(15)
############################################################
turtle.up()
turtle.goto(-250,-50)
turtle.down()
turtle.color("orange")
turtle.write("Happy Independence Day 2019",font=("Comic Sans MS", 28, "bold"))
turtle.up()
turtle.goto(-250,-79)
turtle.down()
turtle.write("By Harsh Bardhan Mishra",font=("Comic Sans MS", 20, "bold"))
turtle.exitonclick()
